"""
Telegram bot conversation states
"""

# Conversation states
MENU = 0
ANALYSIS = 1
SIGNALS = 2
CHOOSE_ANALYSIS = 3
CHOOSE_SIGNALS = 4
CHOOSE_MARKET = 5
CHOOSE_INSTRUMENT = 6
CHOOSE_STYLE = 7
SHOW_RESULT = 8
CHOOSE_TIMEFRAME = 9
SIGNAL_DETAILS = 10
SIGNAL = 11
SUBSCRIBE = 12
BACK_TO_MENU = 13

# Callback data constants
CALLBACK_ANALYSIS_TECHNICAL = "analysis_technical"
CALLBACK_ANALYSIS_SENTIMENT = "analysis_sentiment"
CALLBACK_ANALYSIS_CALENDAR = "analysis_calendar"
CALLBACK_BACK_MENU = "back_menu"
CALLBACK_BACK_ANALYSIS = "back_to_analysis"
CALLBACK_BACK_MARKET = "back_market"
CALLBACK_BACK_INSTRUMENT = "back_instrument"
CALLBACK_BACK_SIGNALS = "back_signals"
CALLBACK_SIGNALS_ADD = "signals_add"
CALLBACK_SIGNALS_MANAGE = "signals_manage"
CALLBACK_MENU_ANALYSE = "menu_analyse"
CALLBACK_MENU_SIGNALS = "menu_signals"

# Market types
MARKET_FOREX = "forex"
MARKET_CRYPTO = "crypto"
MARKET_COMMODITIES = "commodities"
MARKET_INDICES = "indices"

# Timeframes
TIMEFRAME_1M = "1m"
TIMEFRAME_5M = "5m"
TIMEFRAME_15M = "15m"
TIMEFRAME_30M = "30m"
TIMEFRAME_1H = "1h"
TIMEFRAME_4H = "4h"
TIMEFRAME_1D = "1d"

# Menu states
SHOW_PREFERENCES = 8
MANAGE_PREFERENCES = 9
DELETE_PREFERENCE = 10
EDIT_PREFERENCE = 11

# Signal states
SIGNAL_MENU = 20
SIGNAL_CONFIRM = 21
SIGNAL_ANALYSIS = 22
SIGNAL_SETTINGS = 23

# Analysis states
ANALYSIS_MENU = 30
TECHNICAL_ANALYSIS = 31
SENTIMENT_ANALYSIS = 32
CALENDAR_ANALYSIS = 33

# Settings states
SETTINGS_MENU = 40
NOTIFICATION_SETTINGS = 41
RISK_SETTINGS = 42
STYLE_SETTINGS = 43

# Error states
ERROR = 99 
