"""
Telegram bot conversation states
"""

# Menu states
MENU = 0
SHOW_RESULT = 1
CHOOSE_MARKET = 2
CHOOSE_INSTRUMENT = 3
CHOOSE_ANALYSIS = 4
CHOOSE_TIMEFRAME = 5
CHOOSE_STYLE = 6
CONFIRM_PREFERENCE = 7
SHOW_PREFERENCES = 8
MANAGE_PREFERENCES = 9
DELETE_PREFERENCE = 10
EDIT_PREFERENCE = 11

# Signal states
SIGNAL_MENU = 20
SIGNAL_CONFIRM = 21
SIGNAL_ANALYSIS = 22
SIGNAL_SETTINGS = 23

# Analysis states
ANALYSIS_MENU = 30
TECHNICAL_ANALYSIS = 31
SENTIMENT_ANALYSIS = 32
CALENDAR_ANALYSIS = 33

# Settings states
SETTINGS_MENU = 40
NOTIFICATION_SETTINGS = 41
RISK_SETTINGS = 42
STYLE_SETTINGS = 43

# Error states
ERROR = 99 
